### ISSUE TITLE
See if it works against Qt 5.6.0 release

### ISSUE THREAD

**Issue by nsuke** [nsuke/protobuf-qml#11]

**Comment by JosephMillsAtWork** [comment]
I can say that this does not work for 5.6 or 5.7 the array buffer is expecting different amounts of argument.

**Comment by nsuke** [comment]
@JosephMillsAtWork thanks for the info.
Didn't know the debian peculiarity.
It may be due to the fact that they have separate packages for private headers, but IMO they may well put versioned dirs to PRIVATE_INCLUDE_DIRS as it wouldn't do any harm even when absent.

Anyway, as Qt 5.8 will have ArrayBuffer <--> QByteArray auto-conversion, private header usages here will hopefully go away eventually.

Just FYI, I've filed a cmake private header [issue](https://bugs.archlinux.org/task/48786?project=1&cat%5B0%5D=2&string=qt5-declarative) to ArchLinux.
